[build]
  command = "npx prisma generate && npm run build"
  publish = ".next"

[build.environment]
  NODE_OPTIONS = "--max-old-space-size=4096"

[functions]
  included_files = ["data/presets/**"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[edge_functions]]
  function = "inject-ga"
  path = "/*"

[context.production.environment]
  NEXT_PUBLIC_SITE_URL = "https://vierradev.com"
