-- V2 baseline migration.
--
-- The v2 multi-tenant schema (companies, company_memberships, user_preferences,
-- platform_tokens, client_billing, contacts, email provider models, signing
-- sessions, blog models, marketing tracker, etc.) was applied directly from
-- .claude/schema_v2.sql outside Prisma's migration tracking system.
--
-- This empty migration file serves as the Prisma baseline: it declares that
-- the database is already in the v2 state. Mark it as applied WITHOUT running
-- it by executing:
--
--   npx prisma migrate resolve --applied 20260625100000_v2_baseline
--
-- All subsequent schema changes must go through `prisma migrate dev`.
